{% set name = "pytest-ordering" %}
{% set version = "0.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://github.com/ftobia/{{ name }}/archive/{{ version }}.tar.gz"
  sha256: c1149011a3bec662d4dd92427197bd5d02546f380b3568eb6217efb743614309

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - pytest
    - python {{ python_min }}
    - setuptools
  run:
    - pytest
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - pytest_ordering

about:
  home: "https://github.com/ftobia/pytest-ordering"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "pytest plugin to run your tests in a specific order"

extra:
  recipe-maintainers:
    - jni
